In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.5'

In [3]:
a = np.array([1,2,3,4])

In [5]:
a

array([1, 2, 3, 4])

In [6]:
nd1 = np.array([[1,2],[3,4]])

In [7]:
nd1

array([[1, 2],
       [3, 4]])

In [9]:
nd1.ndim

2

In [11]:
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

In [13]:
nd1.shape

(2, 2)

In [25]:
len(nd1.shape), 1

(2, 1)

In [83]:
np.random.seed(1)

In [92]:
np.random.randn()

-0.2493703754774101

In [84]:
np.random.rand(2,3) # 0.0 < x < 1.0

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04],
       [3.02332573e-01, 1.46755891e-01, 9.23385948e-02]])

In [94]:
b = np.array([[1,2,3],[4,5,6]])

In [95]:
b[0,1]

2

In [96]:
b[0]

array([1, 2, 3])

In [97]:
b[0][1]

2

In [99]:
b.shape # axis = 0 행 axis = 1 열, axis = 3, ... 7 ... 

(2, 3)

In [100]:
b[0,1] = 9

In [101]:
b

array([[1, 9, 3],
       [4, 5, 6]])

In [102]:
b.reshape(3,2)

array([[1, 9],
       [3, 4],
       [5, 6]])

In [103]:
c = np.arange(18)

In [104]:
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [105]:
c.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [109]:
c.reshape(len(c),1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17]])

In [111]:
c.reshape(6,-1)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [112]:
c.reshape(-1,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17]])

In [118]:
z = np.zeros((3,4)) # ()를 넣어줘야한다. why?? 

In [121]:
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [122]:
o = np.ones((3,4))

In [123]:
o

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [125]:
f = np.full((3,4),7)

In [127]:
f

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

In [130]:
e = np.eye(4)

In [131]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [138]:
e = e.astype(np.float32)

In [139]:
e

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [160]:
ls = list(range(10000000))

In [167]:
import time
start = time.time() 
[x*2 for x in ls] 
print("time :", time.time() - start)  


time : 1.9653961658477783


In [168]:
import time
start = time.time() 
np.array(ls)*2
print("time :", time.time() - start)  

time : 0.9376633167266846


In [169]:
a = np.arange(5)

In [172]:
b = np.arange(10,15)

In [173]:
a+b

array([10, 12, 14, 16, 18])

In [174]:
a*b

array([ 0, 11, 24, 39, 56])

In [175]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

In [176]:
x+y

array([[ 6,  8],
       [10, 12]])

In [177]:
x*y # 내적 아님.

array([[ 5, 12],
       [21, 32]])

In [178]:
np.dot(x,y)

array([[19, 22],
       [43, 50]])

In [180]:
a[::-1]

array([4, 3, 2, 1, 0])